#!/bin/bash

# Indepentent of DL monitor
setxkbmap is &                                  # Map keyboard
xsettingsd &                                    # Theme manager
xsetroot -cursor_name left_ptr &                # Prevent cursor from being an X
albert &                                        # Launcher
picom &                                         # Compositor
(pgrep -x sxhkd > /dev/null || sxhkd ~/.config/sxhkd/sxhkdrc) &           # Keyboard shortcuts

nitrogen --force-setter=xinerama --restore &    # Wallpaper
$HOME/.config/polybar/scripts/launch.sh &       # Taskbar
if [[ -z "$( pidof redshift )" ]]; then 
  redshift -l 64:-21 &
fi &
(pgrep -x polydock || polydock) &

bspc monitor $( connected-primary-monitor ) -d I II III IV V VI &

( xrandr-set-provider-output-source && (

  # Exclusive to DL monitor
  if [[ -n "$( connected-DVI-monitors )" ]]; then
  
      # Init delay for partially dependent commands
      init-DL-monitor --portrait && sleep 5
  
      # Map desktops to DL monitor
      bspc monitor $( connected-DVI-monitors ) -d VII VIII IX X 
  
      nitrogen --force-setter=xinerama --restore &    # Wallpaper
      $HOME/.config/polybar/launch.sh &               # Taskbar
  
      bspc rule -a 'VirtualBox Manager' desktop=^10 follow=on state=tiled
      bspc rule -a 'VirtualBox Machine' desktop=^10 follow=on state=fullscreen
      bspc rule -a 'VirtualBoxVM' desktop=^10 follow=on state=floating
  fi &

  ) & ) &

# Indepentent of DL monitor
bspc rule -a albert focus=on border=off
bspc rule -a Spotify desktop=^6
bspc rule -a "endeavour" state=floating rectangle=1200x800+360+140
bspc rule -a "Notorious" state=floating
bspc rule -a "solanum" state=floating
bspc config border_width            2
bspc config window_gap              10
bspc config top_padding             10
bspc config focused_border_color    "#cdd6f4"
bspc config split_ratio             0.5
bspc config gapless_monocle         true

